name = "advanced/escrow"
version = "0.0.0"
compiler = "v1.1.21"
plutus = "v3"
license = "Apache-2.0"
description = "Aiken contracts for project 'advanced/escrow'"

[repository]
user = "advanced"
project = "escrow"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "2.2.0"
source = "github"

[config]
